DROP TABLE IF EXISTS PLAYERS;
CREATE TABLE PLAYERS(
   PLAYER_ID INTEGER PRIMARY KEY
  ,NAME VARCHAR(100) UNIQUE
  ,BIRTH_DATE TIMESTAMP
  ,VERSION INTEGER
  );
  
DROP TABLE IF EXISTS TEAMS;
CREATE TABLE TEAMS(
   TEAM_ID INTEGER PRIMARY KEY
  ,NAME VARCHAR(100)
  );


