DROP TABLE PLAYERS;
CREATE TABLE PLAYERS(
   PLAYER_ID IDENTITY PRIMARY KEY
  ,NAME VARCHAR(100)
  ,BIRTH_DATE DATE
  ,VERSION INT
  );
  
DROP TABLE TEAMS;
CREATE TABLE TEAMS(
   TEAM_ID IDENTITY PRIMARY KEY
  ,NAME VARCHAR(100)
  );
